pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git credentialsId: 'mlrBitbucket', url:
                    'https://martalribeiro@bitbucket.org/martalribeiro/devops-19-20-a-1191779.git'
            }
        }
        stage('Assemble') {
            steps {
                dir('ca3/Parte2/tut_basic_gradle') {
                    echo 'Building...'
                    sh 'chmod +x gradlew'
                    sh './gradlew assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('ca3/Parte2/tut_basic_gradle') {
                    echo 'Building...'
                    sh 'chmod +x gradlew'
                    sh './gradlew test'
                    sh 'touch build/test-results/test/*.xml'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage ('Javadoc'){
            steps {
                dir('ca3/Parte2/tut_basic_gradle') {
                    echo 'Publishing javadoc...'
                    sh 'chmod +x gradlew'
                    sh './gradlew javadoc'
                    publishHTML([
                                reportName: 'Javadoc',
                                reportDir: 'build/docs/javadoc/',
                                reportFiles: 'index.html',
                                keepAll: true,
                                alwaysLinkToLastBuild: false,
                                allowMissing: false
                                ])
                }
            }
        }
        stage('Archive') {
            steps {
                dir('ca3/Parte2/tut_basic_gradle') {
                    sh 'pwd'
                    echo 'Archiving...'
                    archiveArtifacts 'build/libs/*.war'
                }
            }
        }
        stage ('Docker Image') {
            steps {
                dir('ca5/Parte2') {
                    script {
                        sh 'docker login -u="martalribeiro" -p="devopsMLR"'
                        sh 'docker build --tag spring_app_tut .'
                        sh 'docker tag spring_app_tut martalribeiro/devops2019-2020:spring_app_tut'
                        sh 'docker push martalribeiro/devops2019-2020:spring_app_tut'
                    }
                }
            }
        }
    }
}
